// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type SchedulesBuilding string

const (
	SchedulesBuildingCode   SchedulesBuilding = "code"
	SchedulesBuildingNumber SchedulesBuilding = "number"
)

func (e *SchedulesBuilding) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulesBuilding(s)
	case string:
		*e = SchedulesBuilding(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulesBuilding: %T", src)
	}
	return nil
}

type NullSchedulesBuilding struct {
	SchedulesBuilding SchedulesBuilding
	Valid             bool // Valid is true if SchedulesBuilding is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulesBuilding) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulesBuilding, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulesBuilding.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulesBuilding) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulesBuilding), nil
}

type SectionsStatus string

const (
	SectionsStatusO SectionsStatus = "O"
	SectionsStatusC SectionsStatus = "C"
	SectionsStatusX SectionsStatus = "X"
)

func (e *SectionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SectionsStatus(s)
	case string:
		*e = SectionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SectionsStatus: %T", src)
	}
	return nil
}

type NullSectionsStatus struct {
	SectionsStatus SectionsStatus
	Valid          bool // Valid is true if SectionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSectionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SectionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SectionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSectionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SectionsStatus), nil
}

type SectionsType string

const (
	SectionsTypeR  SectionsType = "R"
	SectionsTypeN  SectionsType = "N"
	SectionsTypeOL SectionsType = "OL"
	SectionsTypeH  SectionsType = "H"
	SectionsTypeBL SectionsType = "BL"
)

func (e *SectionsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SectionsType(s)
	case string:
		*e = SectionsType(s)
	default:
		return fmt.Errorf("unsupported scan type for SectionsType: %T", src)
	}
	return nil
}

type NullSectionsType struct {
	SectionsType SectionsType
	Valid        bool // Valid is true if SectionsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSectionsType) Scan(value interface{}) error {
	if value == nil {
		ns.SectionsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SectionsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSectionsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SectionsType), nil
}

type Building struct {
	Number    string
	Code      sql.NullString
	Name      sql.NullString
	OffCampus sql.NullBool
}

type Class struct {
	CrseID          uint32
	CrseOfferNbr    uint32
	Strm            uint32
	SessionCode     string
	ClassSection    string
	Subject         string
	CatalogNbr      string
	Descr           string
	Topic           string
	ClassNbr        uint32
	SsrComponent    string
	Units           uint32
	EnrlStat        string
	ClassStat       string
	ClassType       string
	SchedulePrint   string
	EnrlCap         uint32
	EnrlTot         uint32
	Institution     string
	AcadOrg         string
	AcadGroup       string
	AcadCareer      string
	InstructionMode string
	CourseDescrlong string
}

type Course struct {
	ID          uint32
	Quarter     uint16
	Department  uint32
	Course      string
	Credits     uint8
	Title       string
	Description string
}

type Department struct {
	ID      uint32
	School  uint32
	Number  sql.NullInt16
	Code    sql.NullString
	Title   string
	Qtrnums sql.NullString
}

type Instructor struct {
	CrseID       int32
	CrseOfferNbr int32
	Strm         int32
	SessionCode  string
	ClassSection string
	ClassMtgNbr  int32
	LastName     string
	FirstName    string
}

type Meeting struct {
	CrseID           int32
	CrseOfferNbr     int32
	Strm             int32
	SessionCode      string
	ClassSection     string
	ClassMtgNbr      int32
	StartDt          time.Time
	EndDt            time.Time
	Bldg             string
	RoomNbr          string
	MeetingTimeStart time.Time
	MeetingTimeEnd   time.Time
	Mon              string
	Tues             string
	Wed              string
	Thurs            string
	Fri              string
	Sat              string
	Sun              string
}

type Quarter struct {
	Quarter uint16
	Start   time.Time
	End     time.Time
}

type Schedule struct {
	ID               uint32
	Oldid            sql.NullString
	Datelastaccessed time.Time
	Startday         bool
	Endday           bool
	Starttime        uint16
	Endtime          uint16
	Building         SchedulesBuilding
	Quarter          sql.NullInt16
	Image            bool
}

type Schedulecourse struct {
	ID       uint32
	Schedule uint32
	Section  uint32
}

type Schedulenoncourse struct {
	ID       uint32
	Schedule uint32
	Title    string
	Day      bool
	Start    uint16
	End      uint16
}

type School struct {
	ID     uint32
	Number sql.NullInt16
	Code   sql.NullString
	Title  string
}

type Scrapelog struct {
	ID              uint32
	Timestarted     int32
	Timeended       int32
	Quartersadded   uint8
	Coursesadded    uint32
	Coursesupdated  uint32
	Sectionsadded   uint32
	Sectionsupdated uint32
	Failures        uint32
}

type Section struct {
	ID         uint32
	Course     uint32
	Section    string
	Title      string
	Type       SectionsType
	Status     SectionsStatus
	Instructor string
	Maxenroll  uint16
	Curenroll  uint16
}

type Time struct {
	ID       uint32
	Section  uint32
	Day      bool
	Start    uint16
	End      uint16
	Building sql.NullString
	Room     sql.NullString
}
