// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	DeleteSectionTimes(ctx context.Context, section uint32) error
	// Fetches distinct courses from the temp classes table (quarter-era data, strm < 20130).
	GetClassesForQuarterTerms(ctx context.Context) ([]GetClassesForQuarterTermsRow, error)
	// COURSES
	// Non-cancelled courses for a department and term (getCourses endpoint).
	GetCoursesByDepartmentAndTerm(ctx context.Context, arg GetCoursesByDepartmentAndTermParams) ([]GetCoursesByDepartmentAndTermRow, error)
	// Used when term <= 20130: returns number only.
	GetDepartmentsByQuarterTerm(ctx context.Context, arg GetDepartmentsByQuarterTermParams) ([]GetDepartmentsByQuarterTermRow, error)
	// DEPARTMENTS
	// Used when term > 20130: returns code, concatenates numbers.
	GetDepartmentsBySemesterTerm(ctx context.Context, arg GetDepartmentsBySemesterTermParams) ([]GetDepartmentsBySemesterTermRow, error)
	// IMPORT TOOL
	// First pass: get distinct terms and date ranges from the temp meeting table.
	GetMeetingTerms(ctx context.Context) ([]GetMeetingTermsRow, error)
	GetQuarterDates(ctx context.Context, quarter uint16) (GetQuarterDatesRow, error)
	// SCHEDULES
	GetSchedule(ctx context.Context, id uint32) (GetScheduleRow, error)
	GetScheduleByOldID(ctx context.Context, oldid sql.NullString) (uint32, error)
	GetScheduleCourses(ctx context.Context, schedule uint32) ([]uint32, error)
	GetScheduleNonCourses(ctx context.Context, schedule uint32) ([]GetScheduleNonCoursesRow, error)
	// SCHOOLS
	GetSchools(ctx context.Context) ([]School, error)
	// Used when term <= 20130.
	GetSchoolsByQuarterTerm(ctx context.Context) ([]GetSchoolsByQuarterTermRow, error)
	// Used when term > 20130.
	GetSchoolsBySemesterTerm(ctx context.Context) ([]GetSchoolsBySemesterTermRow, error)
	// STATUS
	GetScrapeLog(ctx context.Context) ([]Scrapelog, error)
	// Used by getCourse when term <= 20130: joins department by number.
	GetSectionByCourseQuarterTerm(ctx context.Context, arg GetSectionByCourseQuarterTermParams) (GetSectionByCourseQuarterTermRow, error)
	// Used by getCourse when term > 20130: joins department by code.
	GetSectionByCourseSemesterTerm(ctx context.Context, arg GetSectionByCourseSemesterTermParams) (GetSectionByCourseSemesterTermRow, error)
	// SECTIONS
	// Used by getCourseBySectionId (without description).
	GetSectionByID(ctx context.Context, id uint32) (GetSectionByIDRow, error)
	// Used by getCourseBySectionId with description=true (courseForSection endpoint).
	GetSectionByIDWithDescription(ctx context.Context, id uint32) (GetSectionByIDWithDescriptionRow, error)
	// Fetches the first instructor for a section from the temp instructors table.
	GetSectionInstructor(ctx context.Context, arg GetSectionInstructorParams) (string, error)
	// Fetches meeting patterns from the temp meeting table for a section.
	GetSectionMeetings(ctx context.Context, arg GetSectionMeetingsParams) ([]GetSectionMeetingsRow, error)
	// Used by getSections: all non-cancelled sections with course and department info.
	GetSectionsByCourse(ctx context.Context, course uint32) ([]GetSectionsByCourseRow, error)
	// Fetches sections from the temp classes table for a given course/term/session.
	GetTempSections(ctx context.Context, arg GetTempSectionsParams) ([]GetTempSectionsRow, error)
	// TERMS / QUARTERS
	GetTerms(ctx context.Context) ([]uint16, error)
	// TIMES
	// Used by getMeetingInfo and the getSections time lookup.
	GetTimesBySection(ctx context.Context, section uint32) ([]GetTimesBySectionRow, error)
	// Replaces the InsertOrUpdateCourse stored procedure used by processDump.
	InsertOrUpdateCourse(ctx context.Context, arg InsertOrUpdateCourseParams) (sql.Result, error)
	InsertSchedule(ctx context.Context, arg InsertScheduleParams) (sql.Result, error)
	InsertScheduleCourse(ctx context.Context, arg InsertScheduleCourseParams) error
	InsertScheduleNonCourse(ctx context.Context, arg InsertScheduleNonCourseParams) error
	InsertScrapeLog(ctx context.Context, arg InsertScrapeLogParams) error
	InsertTime(ctx context.Context, arg InsertTimeParams) error
	// pruneSchedules
	// Deletes schedules not accessed in the last 90 days.
	// The caller computes the cutoff timestamp and passes it as a parameter.
	PruneOldSchedules(ctx context.Context, datelastaccessed time.Time) (sql.Result, error)
	SetScheduleImage(ctx context.Context, id uint32) error
	// Updates datelastaccessed; called before every GET to confirm existence and record access.
	TouchSchedule(ctx context.Context, id uint32) error
	UpsertDepartmentsFromClasses(ctx context.Context) error
	UpsertQuarter(ctx context.Context, arg UpsertQuarterParams) error
	UpsertSchoolsFromClasses(ctx context.Context) error
	// Replaces the InsertOrUpdateSection stored procedure used by processDump.
	UpsertSection(ctx context.Context, arg UpsertSectionParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
