// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteSectionTimes = `-- name: DeleteSectionTimes :exec
DELETE FROM times WHERE section = ?
`

func (q *Queries) DeleteSectionTimes(ctx context.Context, section uint32) error {
	_, err := q.db.ExecContext(ctx, deleteSectionTimes, section)
	return err
}

const getClassesForQuarterTerms = `-- name: GetClassesForQuarterTerms :many
SELECT strm, subject, units, acad_org, catalog_nbr, descr, course_descrlong,
       crse_id, crse_offer_nbr, session_code
FROM classes
WHERE strm < 20130
GROUP BY crse_id, strm, session_code
`

type GetClassesForQuarterTermsRow struct {
	Strm            uint32
	Subject         string
	Units           uint32
	AcadOrg         string
	CatalogNbr      string
	Descr           string
	CourseDescrlong string
	CrseID          uint32
	CrseOfferNbr    uint32
	SessionCode     string
}

// Fetches distinct courses from the temp classes table (quarter-era data, strm < 20130).
func (q *Queries) GetClassesForQuarterTerms(ctx context.Context) ([]GetClassesForQuarterTermsRow, error) {
	rows, err := q.db.QueryContext(ctx, getClassesForQuarterTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassesForQuarterTermsRow
	for rows.Next() {
		var i GetClassesForQuarterTermsRow
		if err := rows.Scan(
			&i.Strm,
			&i.Subject,
			&i.Units,
			&i.AcadOrg,
			&i.CatalogNbr,
			&i.Descr,
			&i.CourseDescrlong,
			&i.CrseID,
			&i.CrseOfferNbr,
			&i.SessionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesByDepartmentAndTerm = `-- name: GetCoursesByDepartmentAndTerm :many

SELECT c.title, c.course, c.description, c.id, d.number, d.code
FROM sections AS s
JOIN courses AS c ON s.course = c.id
JOIN departments AS d ON d.id = c.department
WHERE c.department = ?
  AND quarter = ?
  AND s.status != 'X'
GROUP BY c.id
ORDER BY course
`

type GetCoursesByDepartmentAndTermParams struct {
	Department uint32
	Quarter    uint16
}

type GetCoursesByDepartmentAndTermRow struct {
	Title       string
	Course      string
	Description string
	ID          uint32
	Number      sql.NullInt16
	Code        sql.NullString
}

// COURSES
// Non-cancelled courses for a department and term (getCourses endpoint).
func (q *Queries) GetCoursesByDepartmentAndTerm(ctx context.Context, arg GetCoursesByDepartmentAndTermParams) ([]GetCoursesByDepartmentAndTermRow, error) {
	rows, err := q.db.QueryContext(ctx, getCoursesByDepartmentAndTerm, arg.Department, arg.Quarter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesByDepartmentAndTermRow
	for rows.Next() {
		var i GetCoursesByDepartmentAndTermRow
		if err := rows.Scan(
			&i.Title,
			&i.Course,
			&i.Description,
			&i.ID,
			&i.Number,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartmentsByQuarterTerm = `-- name: GetDepartmentsByQuarterTerm :many
SELECT id, title, number
FROM departments AS d
WHERE school = ?
  AND (SELECT COUNT(*) FROM courses AS c WHERE c.department = d.id AND quarter = ?) >= 1
  AND number IS NOT NULL
ORDER BY id
`

type GetDepartmentsByQuarterTermParams struct {
	School  uint32
	Quarter uint16
}

type GetDepartmentsByQuarterTermRow struct {
	ID     uint32
	Title  string
	Number sql.NullInt16
}

// Used when term <= 20130: returns number only.
func (q *Queries) GetDepartmentsByQuarterTerm(ctx context.Context, arg GetDepartmentsByQuarterTermParams) ([]GetDepartmentsByQuarterTermRow, error) {
	rows, err := q.db.QueryContext(ctx, getDepartmentsByQuarterTerm, arg.School, arg.Quarter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDepartmentsByQuarterTermRow
	for rows.Next() {
		var i GetDepartmentsByQuarterTermRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepartmentsBySemesterTerm = `-- name: GetDepartmentsBySemesterTerm :many

SELECT id, title, code, GROUP_CONCAT(number, ', ') AS number
FROM departments AS d
WHERE school = ?
  AND (SELECT COUNT(*) FROM courses AS c WHERE c.department = d.id AND quarter = ?) >= 1
  AND code IS NOT NULL
GROUP BY code
ORDER BY code
`

type GetDepartmentsBySemesterTermParams struct {
	School  uint32
	Quarter uint16
}

type GetDepartmentsBySemesterTermRow struct {
	ID     uint32
	Title  string
	Code   sql.NullString
	Number sql.NullString
}

// DEPARTMENTS
// Used when term > 20130: returns code, concatenates numbers.
func (q *Queries) GetDepartmentsBySemesterTerm(ctx context.Context, arg GetDepartmentsBySemesterTermParams) ([]GetDepartmentsBySemesterTermRow, error) {
	rows, err := q.db.QueryContext(ctx, getDepartmentsBySemesterTerm, arg.School, arg.Quarter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDepartmentsBySemesterTermRow
	for rows.Next() {
		var i GetDepartmentsBySemesterTermRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeetingTerms = `-- name: GetMeetingTerms :many

SELECT strm, start_dt, end_dt FROM meeting GROUP BY strm
`

type GetMeetingTermsRow struct {
	Strm    int32
	StartDt time.Time
	EndDt   time.Time
}

// IMPORT TOOL
// First pass: get distinct terms and date ranges from the temp meeting table.
func (q *Queries) GetMeetingTerms(ctx context.Context) ([]GetMeetingTermsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetingTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeetingTermsRow
	for rows.Next() {
		var i GetMeetingTermsRow
		if err := rows.Scan(&i.Strm, &i.StartDt, &i.EndDt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuarterDates = `-- name: GetQuarterDates :one
SELECT start, end FROM quarters WHERE quarter = ?
`

type GetQuarterDatesRow struct {
	Start time.Time
	End   time.Time
}

func (q *Queries) GetQuarterDates(ctx context.Context, quarter uint16) (GetQuarterDatesRow, error) {
	row := q.db.QueryRowContext(ctx, getQuarterDates, quarter)
	var i GetQuarterDatesRow
	err := row.Scan(&i.Start, &i.End)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one

SELECT startday, endday, starttime, endtime, building, quarter,
       CAST(image AS unsigned) AS image
FROM schedules
WHERE id = ?
`

type GetScheduleRow struct {
	Startday  bool
	Endday    bool
	Starttime uint16
	Endtime   uint16
	Building  SchedulesBuilding
	Quarter   sql.NullInt16
	Image     int64
}

// SCHEDULES
func (q *Queries) GetSchedule(ctx context.Context, id uint32) (GetScheduleRow, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, id)
	var i GetScheduleRow
	err := row.Scan(
		&i.Startday,
		&i.Endday,
		&i.Starttime,
		&i.Endtime,
		&i.Building,
		&i.Quarter,
		&i.Image,
	)
	return i, err
}

const getScheduleByOldID = `-- name: GetScheduleByOldID :one
SELECT id FROM schedules WHERE oldid = ?
`

func (q *Queries) GetScheduleByOldID(ctx context.Context, oldid sql.NullString) (uint32, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByOldID, oldid)
	var id uint32
	err := row.Scan(&id)
	return id, err
}

const getScheduleCourses = `-- name: GetScheduleCourses :many
SELECT section FROM schedulecourses WHERE schedule = ?
`

func (q *Queries) GetScheduleCourses(ctx context.Context, schedule uint32) ([]uint32, error) {
	rows, err := q.db.QueryContext(ctx, getScheduleCourses, schedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uint32
	for rows.Next() {
		var section uint32
		if err := rows.Scan(&section); err != nil {
			return nil, err
		}
		items = append(items, section)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleNonCourses = `-- name: GetScheduleNonCourses :many
SELECT id, title, day, start, end FROM schedulenoncourses WHERE schedule = ?
`

type GetScheduleNonCoursesRow struct {
	ID    uint32
	Title string
	Day   bool
	Start uint16
	End   uint16
}

func (q *Queries) GetScheduleNonCourses(ctx context.Context, schedule uint32) ([]GetScheduleNonCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, getScheduleNonCourses, schedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScheduleNonCoursesRow
	for rows.Next() {
		var i GetScheduleNonCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Day,
			&i.Start,
			&i.End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchools = `-- name: GetSchools :many

SELECT id, number, code, title FROM schools
`

// SCHOOLS
func (q *Queries) GetSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.QueryContext(ctx, getSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []School
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Code,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchoolsByQuarterTerm = `-- name: GetSchoolsByQuarterTerm :many
SELECT id, number AS code, title FROM schools WHERE number IS NOT NULL ORDER BY number
`

type GetSchoolsByQuarterTermRow struct {
	ID    uint32
	Code  sql.NullInt16
	Title string
}

// Used when term <= 20130.
func (q *Queries) GetSchoolsByQuarterTerm(ctx context.Context) ([]GetSchoolsByQuarterTermRow, error) {
	rows, err := q.db.QueryContext(ctx, getSchoolsByQuarterTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSchoolsByQuarterTermRow
	for rows.Next() {
		var i GetSchoolsByQuarterTermRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchoolsBySemesterTerm = `-- name: GetSchoolsBySemesterTerm :many
SELECT id, code, title FROM schools WHERE code IS NOT NULL ORDER BY code
`

type GetSchoolsBySemesterTermRow struct {
	ID    uint32
	Code  sql.NullString
	Title string
}

// Used when term > 20130.
func (q *Queries) GetSchoolsBySemesterTerm(ctx context.Context) ([]GetSchoolsBySemesterTermRow, error) {
	rows, err := q.db.QueryContext(ctx, getSchoolsBySemesterTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSchoolsBySemesterTermRow
	for rows.Next() {
		var i GetSchoolsBySemesterTermRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScrapeLog = `-- name: GetScrapeLog :many

SELECT id, timeStarted, timeEnded, quartersAdded, coursesAdded, coursesUpdated,
       sectionsAdded, sectionsUpdated, failures
FROM scrapelog
ORDER BY timeStarted DESC
LIMIT 20
`

// STATUS
func (q *Queries) GetScrapeLog(ctx context.Context) ([]Scrapelog, error) {
	rows, err := q.db.QueryContext(ctx, getScrapeLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrapelog
	for rows.Next() {
		var i Scrapelog
		if err := rows.Scan(
			&i.ID,
			&i.Timestarted,
			&i.Timeended,
			&i.Quartersadded,
			&i.Coursesadded,
			&i.Coursesupdated,
			&i.Sectionsadded,
			&i.Sectionsupdated,
			&i.Failures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionByCourseQuarterTerm = `-- name: GetSectionByCourseQuarterTerm :one
SELECT s.id,
       CASE WHEN s.title != '' THEN s.title ELSE c.title END AS title,
       s.instructor, s.curenroll, s.maxenroll, s.type,
       d.number AS department, c.course, c.credits, s.section
FROM sections AS s
JOIN courses AS c ON c.id = s.course
JOIN departments AS d ON d.id = c.department
WHERE c.quarter = ?
  AND d.number = ?
  AND c.course = ?
  AND s.section = ?
`

type GetSectionByCourseQuarterTermParams struct {
	Quarter uint16
	Number  sql.NullInt16
	Course  string
	Section string
}

type GetSectionByCourseQuarterTermRow struct {
	ID         uint32
	Title      interface{}
	Instructor string
	Curenroll  uint16
	Maxenroll  uint16
	Type       SectionsType
	Department sql.NullInt16
	Course     string
	Credits    uint8
	Section    string
}

// Used by getCourse when term <= 20130: joins department by number.
func (q *Queries) GetSectionByCourseQuarterTerm(ctx context.Context, arg GetSectionByCourseQuarterTermParams) (GetSectionByCourseQuarterTermRow, error) {
	row := q.db.QueryRowContext(ctx, getSectionByCourseQuarterTerm,
		arg.Quarter,
		arg.Number,
		arg.Course,
		arg.Section,
	)
	var i GetSectionByCourseQuarterTermRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Instructor,
		&i.Curenroll,
		&i.Maxenroll,
		&i.Type,
		&i.Department,
		&i.Course,
		&i.Credits,
		&i.Section,
	)
	return i, err
}

const getSectionByCourseSemesterTerm = `-- name: GetSectionByCourseSemesterTerm :one
SELECT s.id,
       CASE WHEN s.title != '' THEN s.title ELSE c.title END AS title,
       s.instructor, s.curenroll, s.maxenroll, s.type,
       d.code AS department, c.course, c.credits, s.section
FROM sections AS s
JOIN courses AS c ON c.id = s.course
JOIN departments AS d ON d.id = c.department
WHERE c.quarter = ?
  AND d.code = ?
  AND c.course = ?
  AND s.section = ?
`

type GetSectionByCourseSemesterTermParams struct {
	Quarter uint16
	Code    sql.NullString
	Course  string
	Section string
}

type GetSectionByCourseSemesterTermRow struct {
	ID         uint32
	Title      interface{}
	Instructor string
	Curenroll  uint16
	Maxenroll  uint16
	Type       SectionsType
	Department sql.NullString
	Course     string
	Credits    uint8
	Section    string
}

// Used by getCourse when term > 20130: joins department by code.
func (q *Queries) GetSectionByCourseSemesterTerm(ctx context.Context, arg GetSectionByCourseSemesterTermParams) (GetSectionByCourseSemesterTermRow, error) {
	row := q.db.QueryRowContext(ctx, getSectionByCourseSemesterTerm,
		arg.Quarter,
		arg.Code,
		arg.Course,
		arg.Section,
	)
	var i GetSectionByCourseSemesterTermRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Instructor,
		&i.Curenroll,
		&i.Maxenroll,
		&i.Type,
		&i.Department,
		&i.Course,
		&i.Credits,
		&i.Section,
	)
	return i, err
}

const getSectionByID = `-- name: GetSectionByID :one

SELECT s.id,
       CASE WHEN s.title != '' THEN s.title ELSE c.title END AS title,
       c.id AS courseId,
       s.instructor, s.curenroll, s.maxenroll, s.type,
       c.quarter, c.credits, c.course, s.section,
       d.number, d.code
FROM sections AS s
JOIN courses AS c ON s.course = c.id
JOIN departments AS d ON d.id = c.department
WHERE s.id = ?
`

type GetSectionByIDRow struct {
	ID         uint32
	Title      interface{}
	Courseid   uint32
	Instructor string
	Curenroll  uint16
	Maxenroll  uint16
	Type       SectionsType
	Quarter    uint16
	Credits    uint8
	Course     string
	Section    string
	Number     sql.NullInt16
	Code       sql.NullString
}

// SECTIONS
// Used by getCourseBySectionId (without description).
func (q *Queries) GetSectionByID(ctx context.Context, id uint32) (GetSectionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSectionByID, id)
	var i GetSectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Courseid,
		&i.Instructor,
		&i.Curenroll,
		&i.Maxenroll,
		&i.Type,
		&i.Quarter,
		&i.Credits,
		&i.Course,
		&i.Section,
		&i.Number,
		&i.Code,
	)
	return i, err
}

const getSectionByIDWithDescription = `-- name: GetSectionByIDWithDescription :one
SELECT s.id,
       CASE WHEN s.title != '' THEN s.title ELSE c.title END AS title,
       c.id AS courseId,
       s.instructor, s.curenroll, s.maxenroll, s.type,
       c.quarter, c.credits, c.course, c.description, s.section,
       d.number, d.code
FROM sections AS s
JOIN courses AS c ON s.course = c.id
JOIN departments AS d ON d.id = c.department
WHERE s.id = ?
`

type GetSectionByIDWithDescriptionRow struct {
	ID          uint32
	Title       interface{}
	Courseid    uint32
	Instructor  string
	Curenroll   uint16
	Maxenroll   uint16
	Type        SectionsType
	Quarter     uint16
	Credits     uint8
	Course      string
	Description string
	Section     string
	Number      sql.NullInt16
	Code        sql.NullString
}

// Used by getCourseBySectionId with description=true (courseForSection endpoint).
func (q *Queries) GetSectionByIDWithDescription(ctx context.Context, id uint32) (GetSectionByIDWithDescriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getSectionByIDWithDescription, id)
	var i GetSectionByIDWithDescriptionRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Courseid,
		&i.Instructor,
		&i.Curenroll,
		&i.Maxenroll,
		&i.Type,
		&i.Quarter,
		&i.Credits,
		&i.Course,
		&i.Description,
		&i.Section,
		&i.Number,
		&i.Code,
	)
	return i, err
}

const getSectionInstructor = `-- name: GetSectionInstructor :one
SELECT CONCAT(first_name, ' ', last_name) AS instructor
FROM instructors
WHERE crse_id = ?
  AND crse_offer_nbr = ?
  AND strm = ?
  AND session_code = ?
  AND class_section = ?
LIMIT 1
`

type GetSectionInstructorParams struct {
	CrseID       int32
	CrseOfferNbr int32
	Strm         int32
	SessionCode  string
	ClassSection string
}

// Fetches the first instructor for a section from the temp instructors table.
func (q *Queries) GetSectionInstructor(ctx context.Context, arg GetSectionInstructorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSectionInstructor,
		arg.CrseID,
		arg.CrseOfferNbr,
		arg.Strm,
		arg.SessionCode,
		arg.ClassSection,
	)
	var instructor string
	err := row.Scan(&instructor)
	return instructor, err
}

const getSectionMeetings = `-- name: GetSectionMeetings :many
SELECT bldg, room_nbr, meeting_time_start, meeting_time_end,
       mon, tues, wed, thurs, fri, sat, sun
FROM meeting
WHERE crse_id = ?
  AND crse_offer_nbr = ?
  AND strm = ?
  AND session_code = ?
  AND class_section = ?
`

type GetSectionMeetingsParams struct {
	CrseID       int32
	CrseOfferNbr int32
	Strm         int32
	SessionCode  string
	ClassSection string
}

type GetSectionMeetingsRow struct {
	Bldg             string
	RoomNbr          string
	MeetingTimeStart time.Time
	MeetingTimeEnd   time.Time
	Mon              string
	Tues             string
	Wed              string
	Thurs            string
	Fri              string
	Sat              string
	Sun              string
}

// Fetches meeting patterns from the temp meeting table for a section.
func (q *Queries) GetSectionMeetings(ctx context.Context, arg GetSectionMeetingsParams) ([]GetSectionMeetingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSectionMeetings,
		arg.CrseID,
		arg.CrseOfferNbr,
		arg.Strm,
		arg.SessionCode,
		arg.ClassSection,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSectionMeetingsRow
	for rows.Next() {
		var i GetSectionMeetingsRow
		if err := rows.Scan(
			&i.Bldg,
			&i.RoomNbr,
			&i.MeetingTimeStart,
			&i.MeetingTimeEnd,
			&i.Mon,
			&i.Tues,
			&i.Wed,
			&i.Thurs,
			&i.Fri,
			&i.Sat,
			&i.Sun,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSectionsByCourse = `-- name: GetSectionsByCourse :many
SELECT c.title AS coursetitle, c.course, d.number, d.code, s.section,
       s.instructor, s.id, s.type, s.maxenroll, s.curenroll, s.title AS sectiontitle
FROM sections AS s
JOIN courses AS c ON s.course = c.id
JOIN departments AS d ON d.id = c.department
WHERE s.course = ?
  AND s.status != 'X'
ORDER BY c.course, s.section
`

type GetSectionsByCourseRow struct {
	Coursetitle  string
	Course       string
	Number       sql.NullInt16
	Code         sql.NullString
	Section      string
	Instructor   string
	ID           uint32
	Type         SectionsType
	Maxenroll    uint16
	Curenroll    uint16
	Sectiontitle string
}

// Used by getSections: all non-cancelled sections with course and department info.
func (q *Queries) GetSectionsByCourse(ctx context.Context, course uint32) ([]GetSectionsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getSectionsByCourse, course)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSectionsByCourseRow
	for rows.Next() {
		var i GetSectionsByCourseRow
		if err := rows.Scan(
			&i.Coursetitle,
			&i.Course,
			&i.Number,
			&i.Code,
			&i.Section,
			&i.Instructor,
			&i.ID,
			&i.Type,
			&i.Maxenroll,
			&i.Curenroll,
			&i.Sectiontitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTempSections = `-- name: GetTempSections :many
SELECT class_section, descr, topic, enrl_stat, class_stat, class_type,
       enrl_cap, enrl_tot, instruction_mode, schedule_print
FROM classes
WHERE crse_id = ?
  AND crse_offer_nbr = ?
  AND strm = ?
  AND session_code = ?
`

type GetTempSectionsParams struct {
	CrseID       uint32
	CrseOfferNbr uint32
	Strm         uint32
	SessionCode  string
}

type GetTempSectionsRow struct {
	ClassSection    string
	Descr           string
	Topic           string
	EnrlStat        string
	ClassStat       string
	ClassType       string
	EnrlCap         uint32
	EnrlTot         uint32
	InstructionMode string
	SchedulePrint   string
}

// Fetches sections from the temp classes table for a given course/term/session.
func (q *Queries) GetTempSections(ctx context.Context, arg GetTempSectionsParams) ([]GetTempSectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTempSections,
		arg.CrseID,
		arg.CrseOfferNbr,
		arg.Strm,
		arg.SessionCode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTempSectionsRow
	for rows.Next() {
		var i GetTempSectionsRow
		if err := rows.Scan(
			&i.ClassSection,
			&i.Descr,
			&i.Topic,
			&i.EnrlStat,
			&i.ClassStat,
			&i.ClassType,
			&i.EnrlCap,
			&i.EnrlTot,
			&i.InstructionMode,
			&i.SchedulePrint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTerms = `-- name: GetTerms :many

SELECT quarter FROM quarters ORDER BY quarter DESC
`

// TERMS / QUARTERS
func (q *Queries) GetTerms(ctx context.Context) ([]uint16, error) {
	rows, err := q.db.QueryContext(ctx, getTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uint16
	for rows.Next() {
		var quarter uint16
		if err := rows.Scan(&quarter); err != nil {
			return nil, err
		}
		items = append(items, quarter)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimesBySection = `-- name: GetTimesBySection :many

SELECT t.day, t.start, t.end, b.code, b.number, b.off_campus, t.room
FROM times AS t
JOIN buildings AS b ON b.number = t.building
WHERE t.section = ?
ORDER BY t.day, t.start
`

type GetTimesBySectionRow struct {
	Day       bool
	Start     uint16
	End       uint16
	Code      sql.NullString
	Number    string
	OffCampus sql.NullBool
	Room      sql.NullString
}

// TIMES
// Used by getMeetingInfo and the getSections time lookup.
func (q *Queries) GetTimesBySection(ctx context.Context, section uint32) ([]GetTimesBySectionRow, error) {
	rows, err := q.db.QueryContext(ctx, getTimesBySection, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimesBySectionRow
	for rows.Next() {
		var i GetTimesBySectionRow
		if err := rows.Scan(
			&i.Day,
			&i.Start,
			&i.End,
			&i.Code,
			&i.Number,
			&i.OffCampus,
			&i.Room,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrUpdateCourse = `-- name: InsertOrUpdateCourse :execresult
INSERT INTO courses (quarter, department, course, credits, title, description)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  id          = LAST_INSERT_ID(id),
  credits     = VALUES(credits),
  title       = VALUES(title),
  description = VALUES(description)
`

type InsertOrUpdateCourseParams struct {
	Quarter     uint16
	Department  uint32
	Course      string
	Credits     uint8
	Title       string
	Description string
}

// Replaces the InsertOrUpdateCourse stored procedure used by processDump.
func (q *Queries) InsertOrUpdateCourse(ctx context.Context, arg InsertOrUpdateCourseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertOrUpdateCourse,
		arg.Quarter,
		arg.Department,
		arg.Course,
		arg.Credits,
		arg.Title,
		arg.Description,
	)
}

const insertSchedule = `-- name: InsertSchedule :execresult
INSERT INTO schedules (oldid, startday, endday, starttime, endtime, building, quarter)
VALUES ('', ?, ?, ?, ?, ?, ?)
`

type InsertScheduleParams struct {
	Startday  bool
	Endday    bool
	Starttime uint16
	Endtime   uint16
	Building  SchedulesBuilding
	Quarter   sql.NullInt16
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSchedule,
		arg.Startday,
		arg.Endday,
		arg.Starttime,
		arg.Endtime,
		arg.Building,
		arg.Quarter,
	)
}

const insertScheduleCourse = `-- name: InsertScheduleCourse :exec
INSERT INTO schedulecourses (schedule, section) VALUES (?, ?)
`

type InsertScheduleCourseParams struct {
	Schedule uint32
	Section  uint32
}

func (q *Queries) InsertScheduleCourse(ctx context.Context, arg InsertScheduleCourseParams) error {
	_, err := q.db.ExecContext(ctx, insertScheduleCourse, arg.Schedule, arg.Section)
	return err
}

const insertScheduleNonCourse = `-- name: InsertScheduleNonCourse :exec
INSERT INTO schedulenoncourses (title, day, start, end, schedule) VALUES (?, ?, ?, ?, ?)
`

type InsertScheduleNonCourseParams struct {
	Title    string
	Day      bool
	Start    uint16
	End      uint16
	Schedule uint32
}

func (q *Queries) InsertScheduleNonCourse(ctx context.Context, arg InsertScheduleNonCourseParams) error {
	_, err := q.db.ExecContext(ctx, insertScheduleNonCourse,
		arg.Title,
		arg.Day,
		arg.Start,
		arg.End,
		arg.Schedule,
	)
	return err
}

const insertScrapeLog = `-- name: InsertScrapeLog :exec
INSERT INTO scrapelog
  (timeStarted, timeEnded, quartersAdded, coursesAdded, coursesUpdated,
   sectionsAdded, sectionsUpdated, failures)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScrapeLogParams struct {
	Timestarted     int32
	Timeended       int32
	Quartersadded   uint8
	Coursesadded    uint32
	Coursesupdated  uint32
	Sectionsadded   uint32
	Sectionsupdated uint32
	Failures        uint32
}

func (q *Queries) InsertScrapeLog(ctx context.Context, arg InsertScrapeLogParams) error {
	_, err := q.db.ExecContext(ctx, insertScrapeLog,
		arg.Timestarted,
		arg.Timeended,
		arg.Quartersadded,
		arg.Coursesadded,
		arg.Coursesupdated,
		arg.Sectionsadded,
		arg.Sectionsupdated,
		arg.Failures,
	)
	return err
}

const insertTime = `-- name: InsertTime :exec
INSERT INTO times (section, day, start, end, building, room)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTimeParams struct {
	Section  uint32
	Day      bool
	Start    uint16
	End      uint16
	Building sql.NullString
	Room     sql.NullString
}

func (q *Queries) InsertTime(ctx context.Context, arg InsertTimeParams) error {
	_, err := q.db.ExecContext(ctx, insertTime,
		arg.Section,
		arg.Day,
		arg.Start,
		arg.End,
		arg.Building,
		arg.Room,
	)
	return err
}

const pruneOldSchedules = `-- name: PruneOldSchedules :execresult

DELETE FROM schedules WHERE datelastaccessed < ?
`

// pruneSchedules
// Deletes schedules not accessed in the last 90 days.
// The caller computes the cutoff timestamp and passes it as a parameter.
func (q *Queries) PruneOldSchedules(ctx context.Context, datelastaccessed time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneOldSchedules, datelastaccessed)
}

const setScheduleImage = `-- name: SetScheduleImage :exec
UPDATE schedules SET image = 1 WHERE id = ?
`

func (q *Queries) SetScheduleImage(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, setScheduleImage, id)
	return err
}

const touchSchedule = `-- name: TouchSchedule :exec
UPDATE schedules SET datelastaccessed = NOW() WHERE id = ?
`

// Updates datelastaccessed; called before every GET to confirm existence and record access.
func (q *Queries) TouchSchedule(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, touchSchedule, id)
	return err
}

const upsertDepartmentsFromClasses = `-- name: UpsertDepartmentsFromClasses :exec
INSERT INTO departments (code, school)
SELECT c.acad_org, s.id
FROM classes AS c
JOIN schools AS s ON s.code = c.acad_group
WHERE strm > 2130
GROUP BY c.acad_org
ON DUPLICATE KEY UPDATE school = VALUES(school)
`

func (q *Queries) UpsertDepartmentsFromClasses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, upsertDepartmentsFromClasses)
	return err
}

const upsertQuarter = `-- name: UpsertQuarter :exec
INSERT INTO quarters (quarter, start, end)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE start = VALUES(start), end = VALUES(end)
`

type UpsertQuarterParams struct {
	Quarter uint16
	Start   time.Time
	End     time.Time
}

func (q *Queries) UpsertQuarter(ctx context.Context, arg UpsertQuarterParams) error {
	_, err := q.db.ExecContext(ctx, upsertQuarter, arg.Quarter, arg.Start, arg.End)
	return err
}

const upsertSchoolsFromClasses = `-- name: UpsertSchoolsFromClasses :exec
INSERT INTO schools (code)
SELECT acad_group FROM classes
WHERE acad_group NOT IN (SELECT code FROM schools WHERE code IS NOT NULL)
ON DUPLICATE KEY UPDATE code = code
`

func (q *Queries) UpsertSchoolsFromClasses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, upsertSchoolsFromClasses)
	return err
}

const upsertSection = `-- name: UpsertSection :execresult
INSERT INTO sections (course, section, title, instructor, type, status, maxenroll, curenroll)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  title      = VALUES(title),
  instructor = VALUES(instructor),
  type       = VALUES(type),
  status     = VALUES(status),
  maxenroll  = VALUES(maxenroll),
  curenroll  = VALUES(curenroll)
`

type UpsertSectionParams struct {
	Course     uint32
	Section    string
	Title      string
	Instructor string
	Type       SectionsType
	Status     SectionsStatus
	Maxenroll  uint16
	Curenroll  uint16
}

// Replaces the InsertOrUpdateSection stored procedure used by processDump.
func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertSection,
		arg.Course,
		arg.Section,
		arg.Title,
		arg.Instructor,
		arg.Type,
		arg.Status,
		arg.Maxenroll,
		arg.Curenroll,
	)
}
